### ISSUE TITLE
"File Does Not Exist" after Question

### ISSUE THREAD

**Issue by xdcortes01** [mukulpatnaik/researchgpt#11]
On the demo, after uploading any PDF and entering a question, I get the message "File Does Not Exist".
I tried using different OpenAI APIs and different PDFs.

Consol:
Uncaught (in promise) ReferenceError: error is not defined
    at create_prompt (script.js:152:66)
    at async HTMLButtonElement.<anonymous> (script.js:246:14)

**Comment by dantoac** [comment]
did you try running locally?

**Comment by 1786487276** [comment]
me too

**Comment by zthxxx** [comment]
mee too

**Comment by zthxxx** [comment]
mee too

**Comment by zhuzhunvhai2000** [comment]
metoo!

**Comment by mukulpatnaik** [comment]
Hi all, just pushed a major refactor of the code to make it more efficient and fix all these bugs, please consider updating your local version to the latest changes using git fetch and try again. Thanks!
