### ISSUE TITLE
It seems that the answer is completely different from the article

### ISSUE THREAD

**Issue by LittleGhosts** [mukulpatnaik/researchgpt#17]
I tried to guide into the classic paper "Attention Is All You Need" and asked him what the article mainly talked about and what it said, but GPT returned me medical-related content, which is not formal

![1](https://user-images.githubusercontent.com/36463457/221774624-8eaf0bbc-bae0-4eb8-9662-cc474a4ac4f5.png)

**Comment by zifengdexiatian** [comment]
Yes I found the same question and the answer is irrelevant to the article

**Comment by changh95** [comment]
It seems like the references that are not necessarily related to the main content of the paper are added to the prompt, so the ai gets distracted by them.

**Comment by ohmygoobness** [comment]
same, different paper. I also asked about the paper title and author it gives different result.

**Comment by endolith** [comment]
Same, but I don't think it's referencing any particular paper at all, it's just hallucinating something that sounds right from your prompt

**Comment by mukulpatnaik** [comment]
Hi @changh95 @zifengdexiatian @LittleGhosts @endolith  This is not ideal but asking it questions like "what is the main idea of this paper" would not necessarily return embeddings related to what you are asking. This tool is more for asking more specific questions regarding the contents of the paper or asking any doubts like phrases or concepts you don't understand. Try with some more specific questions regarding the concepts of the paper and let me know if you have the same issue. Thanks :)

**Comment by endolith** [comment]
[ChatPDF ](https://www.chatpdf.com/) does a better job, for comparison:

> Chat with Baujard 2017 - [FRENCH] Report of the experiment VOTER AUTREMENT French presidential election 2017.pdf
> 
>  Bonjour! Nous sommes ravis de vous présenter le compte-rendu de l'expérimentation "VOTER AUTREMENT" lors du premier tour de l'élection présidentielle française en 2017. Cette étude a été menée par une équipe de chercheurs et universitaires de renom.
> 
> Voici trois questions que vous pourriez avoir sur ce fichier :
> 
> * Quels étaient les objectifs de l'expérimentation "VOTER AUTREMENT" ?
> * Quels ont été les résultats de l'expérimentation dans les différentes villes et sur internet ?
> * Quelles sont les implications de cette étude pour les futurs modes de scrutin en France ?
> 
> **Hello**
> 
> Hello! How can I assist you today?
> 
> **What is this paper about?**
> 
> This paper is about experimenting with new voting methods and protocols in order to better understand the functioning of democratic institutions, study the properties of collective decision-making procedures, and analyze the behavior of voters in response to different voting systems. The document aims to report on the first results and lessons learned from this series of experiments. The data provided by these experiments will be used to conduct further research in the future. This information can be found on page 1, sections I-IV.
> 
> **What are the implications on the study of Klingon physiology?**
> 
> I'm sorry, but the paper does not mention anything about the study of Klingon physiology. It focuses solely on experimenting with new voting methods and analyzing the behavior of voters in response to different voting systems.
> 
> **How many voters participated in the experiment?**
> 
> According to the information provided on page 1, a total of 37,739 voluntary participants took part in the experiment to test three randomly selected alternative voting methods before the first round and between the two rounds of the French election.

ResearchGPT just hallucinates unrelated things that sound plausible:

> **Hello**
> 
> This paper explores the potential of using natural language processing (NLP) to improve the accuracy and efficiency of medical diagnoses. The authors present a novel approach to NLP that combines traditional machine learning techniques with deep learning models. The proposed system is evaluated on a dataset of medical records and is shown to outperform existing methods in both accuracy and speed. Additionally, the authors discuss the implications of using NLP in medical diagnostics, as well as potential future applications.
> 
> Page 14: Nb : HSC pour Hérouville Saint Clair....
> 
> Page 0: à Allevard les Bains, Crolles, Grenoble, Hérouville Saint Clair, Strasbourg et sur internet...
> 
> Page 8: Illustration : Bureau expérimental à Crolles...
> 
> **What is this paper about?**
> 
> This paper explores the potential of using machine learning algorithms to detect and classify objects in images. It begins by discussing the challenges of object detection, such as the need for large datasets and the difficulty of accurately recognizing objects in complex scenes. The paper then presents a novel object detection system based on a convolutional neural network (CNN) and a region proposal network (RPN). The system is evaluated on the popular ImageNet dataset and achieves state-of-the-art results. The paper concludes by discussing the potential applications of the proposed system and the challenges that remain to be addressed.
> 
> Page 8: Illustration : Bureau expérimental à Crolles...
> 
> Page 0: vote officiel. Il ne s’agit pas non plus d’un sondage d’opinion . Il s’agit de mieux comprendre le fonctionnement des institutions démocratiques, d’ét...
> 
> Page 2: Cette expérimentation s’inscrit dans la lignée des expérimentations menées en parallèle du premier tour des précé dentes élections présidentielles fra...
> 
> **What are the implications on the study of Klingon physiology?**
> 
> This paper examines the implications of studying Klingon physiology. It begins by discussing the unique physiology of the Klingon species, including their distinctive skeletal structure and their unique cardiovascular system. It then looks at the implications of studying this physiology, such as the potential for understanding the biology of other species, as well as the potential for medical advances. The paper also looks at the ethical considerations of studying the physiology of a non-human species, and how this could affect the perception of the species in the wider world. Finally, the paper concludes by suggesting further research into the implications of studying Klingon physiology, as well as the potential for developing treatments and therapies based on this knowledge.
> 
> Page 12: III.1.1. Une participation élevée et une représentation diversifiée Nous avons pu confirmer par cette nouvelle expérimentation qu’il était possible de...
> 
> Page 17: Les tendances décrites à partir des expérimentations in situ relatives aux différences en vainqueur et en classement se retrouvent dans les résultats ...
> 
> Page 0: vote officiel. Il ne s’agit pas non plus d’un sondage d’opinion . Il s’agit de mieux comprendre le fonctionnement des institutions démocratiques, d’ét...

> 
> **How many voters participated in the experiment?**
> 
> The experiment in question involved a total of 843 voters. The participants were recruited from a variety of sources, including online surveys, social media platforms, and face-to-face interviews. The demographics of the participants were diverse, with a range of ages, genders, and political affiliations represented. The experiment was conducted over a period of two weeks, with each participant completing the survey at least once during that time. The results of the experiment showed that a majority of the participants had a positive opinion of the proposed policy, with 58.3% of the voters in favor of it.
> 
> Page 8: Afin de garantir l’absence de perturbation des scrutins officiels et la totale étanchéité entre l’étude scientifiqu e et les enjeux politiques de la p...
> 
> Page 12: III.1.1. Une participation élevée et une représentation diversifiée Nous avons pu confirmer par cette nouvelle expérimentation qu’il était possible de...
> 
> Page 0: 27 juin 2017 Antoinette Baujard, GATE Lyon Saint Etienne (UMR CNRS 5824), Université de Lyon / Jean Monnet Renaud Blanch, LIG (UMR CNRS 5217) Universi...

The number 843 and 58.3% don't appear in the document at all...
