### ISSUE TITLE
Error: Processing the pdf failed due to excess load. Please try again later. 

### ISSUE THREAD

**Issue by matriim** [mukulpatnaik/researchgpt#18]
Hey,
Thank you for your cool project!

I wanted to try it out and got the following error:
Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.

Is this normal?

**Comment by Abandon339** [comment]
I have the same too

**Comment by Alex-Lord** [comment]
I have the same problem using the 'main-local.py'

**Comment by Xin-GY** [comment]
I have the same too, while using the 'main-local.py'

**Comment by nature1949** [comment]
Me too.

**Comment by MrPeterJin** [comment]
Me too.

**Comment by lxd941213** [comment]
so how to solve it

**Comment by yeloveyou** [comment]
me too

**Comment by mukulpatnaik** [comment]
Hi @nature1949 @lxd941213 @matriim @Abandon339 @yeloveyou @MrPeterJin @Abandon339 @Xin-GY @fatboy1994  please make sure you are on a secure connection (Check the URL of the app https:// at the beginning. If not, add it.) Or just go to this link [here](https://researchgpt.ue.r.appspot.com). 

If you are still facing this issue it may be because the demo is overloaded due to too many people using it at the same time.

Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.

To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)

**Comment by shuaifanfan** [comment]
> Hi @nature1949 @lxd941213 @matriim @Abandon339 @yeloveyou @MrPeterJin @Abandon339 @Xin-GY @fatboy1994 please make sure you are on a secure connection (Check the URL of the app https:// at the beginning. If not, add it.) Or just go to this link [here](https://researchgpt.ue.r.appspot.com).
> 
> If you are still facing this issue it may be because the demo is overloaded due to too many people using it at the same time.
> 
> Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.
> 
> To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)

I'm not a native English speaker, apologize for my language problem. My friend and I run the demo locally, and upload local pdf. We also have this problem. We tried to find the problem.
I changed the port 8080 to 5000. When I upload pdf, there would be a http error 500.
![图片](https://user-images.githubusercontent.com/93373861/223930884-75d05839-82eb-47c0-9ac6-2ee2b4dfd1ff.png)
More specific error is "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"
![图片](https://user-images.githubusercontent.com/93373861/223931597-3e8cbe7c-7010-4a87-9f42-09ecea721703.png)
This is the the part of the js that may be buggy.
![图片](https://user-images.githubusercontent.com/93373861/223930101-73c43fd7-4abe-4217-9613-28ca707366a0.png)
I donot learn much about js, but there must be something wrong with the "process_pdf" in static/js/script.js

**Comment by yeloveyou** [comment]
> > Hi @nature1949 @lxd941213 @matriim @Abandon339 @yeloveyou @MrPeterJin @Abandon339 @Xin-GY @fatboy1994 please make sure you are on a secure connection (Check the URL of the app https:// at the beginning. If not, add it.) Or just go to this link [here](https://researchgpt.ue.r.appspot.com).
> > If you are still facing this issue it may be because the demo is overloaded due to too many people using it at the same time.
> > Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.
> > To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)
> 
> I'm not a native English speaker, apologize for my language problem. My friend and I run the demo locally, and upload local pdf. We also have this problem. We tried to find the problem. I changed the port 8080 to 5000. When I upload pdf, there would be a http error 500. ![图片](https://user-images.githubusercontent.com/93373861/223930884-75d05839-82eb-47c0-9ac6-2ee2b4dfd1ff.png) More specific error is "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" ![图片](https://user-images.githubusercontent.com/93373861/223931597-3e8cbe7c-7010-4a87-9f42-09ecea721703.png) This is the the part of the js that may be buggy. ![图片](https://user-images.githubusercontent.com/93373861/223930101-73c43fd7-4abe-4217-9613-28ca707366a0.png) I donot learn much about js, but there must be something wrong with the "process_pdf" in static/js/script.js

我在本地搭建成功了，如果你和我一样，用了clash for windows，你可以尝试在clash中的setting->System Proxy->Specify Protocol开启即可

**Comment by shuaifanfan** [comment]
> > > Hi @nature1949 @lxd941213 @matriim @Abandon339 @yeloveyou @MrPeterJin @Abandon339 @Xin-GY @fatboy1994 please make sure you are on a secure connection (Check the URL of the app https:// at the beginning. If not, add it.) Or just go to this link [here](https://researchgpt.ue.r.appspot.com).
> > > If you are still facing this issue it may be because the demo is overloaded due to too many people using it at the same time.
> > > Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.
> > > To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)
> > 
> > 
> > I'm not a native English speaker, apologize for my language problem. My friend and I run the demo locally, and upload local pdf. We also have this problem. We tried to find the problem. I changed the port 8080 to 5000. When I upload pdf, there would be a http error 500. ![图片](https://user-images.githubusercontent.com/93373861/223930884-75d05839-82eb-47c0-9ac6-2ee2b4dfd1ff.png) More specific error is "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" ![图片](https://user-images.githubusercontent.com/93373861/223931597-3e8cbe7c-7010-4a87-9f42-09ecea721703.png) This is the the part of the js that may be buggy. ![图片](https://user-images.githubusercontent.com/93373861/223930101-73c43fd7-4abe-4217-9613-28ca707366a0.png) I donot learn much about js, but there must be something wrong with the "process_pdf" in static/js/script.js
> 
> 我在本地搭建成功了，如果你和我一样，用了clash for windows，你可以尝试在clash中的setting->System Proxy->Specify Protocol开启即可

> 十分感谢，我一直用CFW，因为要连接OPEN AI，所以要一直开代理，原来是访问本机地址没有协议头导致的500error。太感谢你了

**Comment by Xin-GY** [comment]
谢谢，我也回去试试。估计问题是一样的，我也是在运行本地配置的时候出现了问题

**Comment by wccccp** [comment]
> 
我cfl已经设置了指定协议 但是还是在报500错误 有什么办法吗

**Comment by phiiil69** [comment]
I have the same issue but I'm running localy: 127.0.0.1:8000
**Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.**
I've just loaded 2 documents.
Phil
