### ISSUE TITLE
can this read Chinese paper?

### ISSUE THREAD

**Issue by elkgir1** [mukulpatnaik/researchgpt#19]

**Comment by MrPeterJin** [comment]
Hi, you may see my implement. It can't read Chinese paper due to the `PyPDF2` package. I have fixed this problem, please refer to [my fork](https://github.com/MrPeterJin/researchgpt)

**Comment by mukulpatnaik** [comment]
@MrPeterJin Really interesting stuff! Might implement some of your changes. Let me know if you'd like to become a collaborator!

**Comment by MrPeterJin** [comment]
> @MrPeterJin Really interesting stuff! Might implement some of your changes. Let me know if you'd like to become a collaborator!

Thank you for your comment! I'm glad that you found my work interesting and I would be happy to collaborate with you.

**Comment by mukulpatnaik** [comment]
@MrPeterJin sent you an email! feel free to submit a pr with your new features!

**Comment by zhangwanshen** [comment]
> 你好，你可以看看我的工具。由于包装原因，它无法阅读中文文件`PyPDF2`。我已经解决了这个问题，请参考[我的fork](https://github.com/MrPeterJin/researchgpt)

您好，请问您的researchgpt私有化部署时需要配置代理吗？

**Comment by MrPeterJin** [comment]
> > 你好，你可以看看我的工具。由于包装原因，它无法阅读中文文件`PyPDF2`。我已经解决了这个问题，请参考[我的fork](https://github.com/MrPeterJin/researchgpt)
> 
> 您好，请问您的researchgpt私有化部署时需要配置代理吗？

您好，是需要的，因为它需要从 OpenAI API 接收信息
