### ISSUE TITLE
Error: Request to OpenAI failed. Please try again.

### ISSUE THREAD

**Issue by xiosi** [mukulpatnaik/researchgpt#21]
i have got error with /reply 500 error.
if i use url，i got NameError: name 'df' is not defined.
if i use document, i got IndexError: single positional indexer is out-of-bounds.
Can you guys help me. Sad!

**Comment by xiosi** [comment]
I run this server in docker container Ubuntu:foxy with python3.8

**Comment by mukulpatnaik** [comment]
Hi, please try using python 3.10 and let me know if you are seeing the same error
