### ISSUE TITLE
ChatGPT API

### ISSUE THREAD

**Issue by goldengrape** [mukulpatnaik/researchgpt#28]
I tried: 
```
r = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", 
            messages=prompt, 
            temperature=0.4, 
            max_tokens=1500)
```
in main-local.py
but doesn't work

**Comment by magicgh** [comment]
`prompt` should be rewritten as an array of dictionaries.
Example:
```python
prompt=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
 ```

**Comment by goldengrape** [comment]
@magicgh 

cool! this works:

```
        messages=[
            {
            "role": "user",
            "content": prompt
            }
        ]
        r = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", 
            messages=messages, 
            temperature=0.4, 
            max_tokens=1500)
        
        answer=(
                r["choices"][0]
                .get("message")
                .get("content")
                .encode("utf8")
                .decode()
            )
```

**Comment by MrPeterJin** [comment]
> @magicgh
> 
> cool! this works:
> 
> ```
>         messages=[
>             {
>             "role": "user",
>             "content": prompt
>             }
>         ]
>         r = openai.ChatCompletion.create(
>             model="gpt-3.5-turbo", 
>             messages=messages, 
>             temperature=0.4, 
>             max_tokens=1500)
>         
>         answer=(
>                 r["choices"][0]
>                 .get("message")
>                 .get("content")
>                 .encode("utf8")
>                 .decode()
>             )
> ```

Hi, I have implemented this in [my fork](https://github.com/MrPeterJin/researchgpt). You can have a try!
