### ISSUE TITLE
save the embedding DataFrame

### ISSUE THREAD

**Issue by goldengrape** [mukulpatnaik/researchgpt#29]
When running locally, the embedding needs to be calculated every time the same PDF is opened, which is somewhat wasteful. It would be best to save the embedding dataframe so that it can be checked before the next use. If the embedding has already been done, it doesn't need to be done again. Additionally, can the embedding dataframe be used as a search index in Zotero?

**Comment by mukulpatnaik** [comment]
Hi @goldengrape I have added a way to store embeddings locally using redis. You can find that implementation [here](https://github.com/mukulpatnaik/researchgpt/blob/main/main-local-redis.py). You have to install redis and run redis-serve in a separate terminal for this to work
