### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

### ISSUE THREAD

**Issue by yeloveyou** [mukulpatnaik/researchgpt#30]
当我开启了代理，上传PDF时候会报错如标题，但我不知道怎么改
When I turn on the proxy, an error is reported when uploading the PDF, but I don't know how to change it

**Comment by yeloveyou** [comment]
![image](https://user-images.githubusercontent.com/51388802/223104495-fb6b8a6f-12c6-4380-9863-136fb0dc8a72.png)

**Comment by mukulpatnaik** [comment]
Sorry I am not sure what your are trying to do, would you mind expanding on the error some more? What proxy are you trying to use and for what? If your issue is regarding ssl, I apologize but I would not be able to help you there
