### ISSUE TITLE
Clarification on variable 'CLOUD_STORAGE_BUCKET'

### ISSUE THREAD

**Issue by Michael-H777** [mukulpatnaik/researchgpt#33]
Hello, 

Thank you for your effort in developing this tool! 

I am trying to deploy a local version of this, however is not sure what is this 'CLOUD_STORAGE_BUCKET' variable. I can tell that its for google cloud, but i am not sure how to setup this BUCKET thing to get this app to work locally. 

If you can provide more detail about this is REAME, that would be great! 

Thanks, 
Michael

**Comment by mukulpatnaik** [comment]
Hi @Michael-H777, sorry for the late response. That was supposed to be for a google cloud deployment that I had for the live version, I realised that most people would want to only use this locally so I have removed it now. I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running `git fetch` to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
