### ISSUE TITLE
Wrong output 

### ISSUE THREAD

**Issue by heyygarvit** [mukulpatnaik/researchgpt#35]
I was asking question "Summarise the paper" on the paper "End-To-End Bias Mitigation: Removing Gender Bias in Deep Learning" 

and it giving me this answer

This paper examines the effects of a new type of drug on a particular medical condition. The study was conducted on a sample of 100 participants, with 50 receiving the drug and 50 receiving a placebo. The results showed that the drug had a significant effect on the condition, with a reduction in symptoms in the group receiving the drug compared to the group receiving the placebo. The study also found that the drug had no adverse side effects. This study provides evidence that this new drug could be a safe and effective treatment for this medical condition.

**Comment by MrPeterJin** [comment]
Hi, you can try [my fork](https://github.com/MrPeterJin/researchgpt). It returns this:
> The paper titled "End-To-End Bias Mitigation: Removing Gender Bias in Deep Learning" presents a framework for increasing fairness in deep learning models by removing gender bias. The paper discusses the problems of gender bias in statistical and deep learning models and presents an end-to-end approach for mitigating such biases. The approach involves pre-processing, in-processing, and post-processing algorithms that were previously applied to statistical models but are now extended to deep learning models. The experiments conducted on gender-biased datasets show that the approach achieves competitive performance while consuming significantly less energy. The paper also discusses the potential applications of the approach beyond benchmark datasets, such as in the domains of privacy and security. The authors encourage further exploration of the end-to-end bias mitigation method as a promising framework for both academics and practitioners. The paper concludes with a discussion of future directions in the field and open-source packages that make fairness research broadly accessible.
