### ISSUE TITLE
Hosting on my site

### ISSUE THREAD

**Issue by ally1969** [mukulpatnaik/researchgpt#4]
I'm trying to host this on my site and when I upload a pdf I get the following errors: 

POST https://[MYSITE]/process_pdf 403
(anonymous) @ script.js:170

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
(anonymous) @ script.js:189
Promise.catch (async)
(anonymous) @ script.js:187

Any help would be appreciated.

**Comment by mukulpatnaik** [comment]
It looks like the server is returning html data in the request which is causing the error. Could you tell me if you are using main.py or main-local.py as the server? Also would you mind sharing the pdf you uploaded so that I can try to recreate the error and debug?
