### ISSUE TITLE
[google cloud deployment] SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by joohayoung** [mukulpatnaik/researchgpt#40]
It worked fine local, but the following error occurred after google cloud deployment.

**SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON**

I think... It seems to be a fetch and .then problem.
JavaScript code expected to receive JSON but got something else instead (probably HTML in the form of a server-side error).

Thanks for any help.

**Comment by mukulpatnaik** [comment]
Hi @joohayoung  my apologies I have moved off google cloud now as it was giving me a lot of issues.  I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running `git fetch` to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
