### ISSUE TITLE
Module "_md5" in main.py could not be resolved!

### ISSUE THREAD

**Issue by piwawa** [mukulpatnaik/researchgpt#41]
Just like this:
![image](https://user-images.githubusercontent.com/46926496/223936972-a98d29ba-3d3a-432a-874d-d23e3fed2b27.png)

I have done "pip install -r requirements.txt", but still have this error in VSCode.

**Comment by mukulpatnaik** [comment]
Hi @piwawa md5 should be a native python library, I'm not exactly sure why you're facing this issue. I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running `git fetch` to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
