### ISSUE TITLE
script.js:192 Uncaught (in promise) ReferenceError: pdfjsLib is not defined

### ISSUE THREAD

**Issue by lkunxyz** [mukulpatnaik/researchgpt#42]
when upload a PDF file， i got this problem:  script.js:192 Uncaught (in promise) ReferenceError: pdfjsLib is not defined
![image](https://user-images.githubusercontent.com/3108757/224190100-dc76ba79-7a37-465d-b2f8-580df8c87b93.png)

**Comment by nickboyabc** [comment]
me too

**Comment by mukulpatnaik** [comment]
Hi @lkunxyz @nickboyabc sorry to hear you're facing these issues. I have made major updates since and launched a new web app on www.dara.chat, you should not be facing any of these errors there. Please let me know if you still do!
