### ISSUE TITLE
Increasing maximum paper length to not run into AttributeError: 'DataFrame' object has no attribute 'embeddings'

### ISSUE THREAD

**Issue by Spoot1RH** [mukulpatnaik/researchgpt#43]
I noticed when putting a pdf with about 30 pages into the program I get the Error: AttributeError: 'DataFrame' object has no attribute 'embeddings'. I think it would be useful that for the time being that the program warns you that the text is too long and cannot be read in.

I understand that the API has a token limit but also a memory, would it be possible to expand the code to splice up longer pdfs so that it can be fed to the api bit by bit in the background.

Further I would like to know what amount of pages on average is a safe number to input for the current build, what are your experiences?

**Comment by mukulpatnaik** [comment]
Hi @Spoot1RH I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running `git fetch` to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!

Consider using the online webapp www.dara.chat, it consists of many optimizations that are not yet public and can handle large pdfs well. Let me know if you're still having issues!
