### ISSUE TITLE
seem doesn't work on AWS EC2 (maybe my wrong setup...)

### ISSUE THREAD

**Issue by michael7908** [mukulpatnaik/researchgpt#45]
After I run root@ip-172-31-2-32:/home/ubuntu/researchgpt# python3 main-local.py

I got these as follows:

 * Serving Flask app 'main-local'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.31.2.32:8080
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 175-455-407

but when I copy http://172.31.2.32:8080 into a Chrome broswer , I got error message:

Unable to reach this site 172.31.2.32 is taking too long to respond.
Please try the following:

check network connection
Check proxy servers and firewalls
Run Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

Any suggestion to fix this? thanks much!

**Comment by SunGaofeng** [comment]
Is the ip 172.31.2.32 a public address? If you didn't changed EC2 instance's name, it seemed to be an  inner address. You can check the public ip of your instance on the AWS console.
