### ISSUE TITLE
[Feature Request] Automatically save the conversation and save the commonly-used prompts for reuse

### ISSUE THREAD

**Issue by longfuxu** [mukulpatnaik/researchgpt#47]
Thank you guys for developing this fantistic app, and it works very well.

- I am wondering if it is possible to automatically save the conversation between the user and chatgpt in a file with the same title as the paper;
- Also, would you also like to add the feature to save the custommer-designed prompts for next-time use?

Thank you

**Comment by phiiil69** [comment]
Hi, which OS do you use to run the app ?

**Comment by Chapoly1305** [comment]
Implemented, please consider review and merge.
