### ISSUE TITLE
Problem when performing the 'python main-local.py'

### ISSUE THREAD

**Issue by JiaLIU99** [mukulpatnaik/researchgpt#49]
Hi, I met this `WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead` when I was performing the `python main-local.py`, and I wonder what I could to handle this.

**Comment by zcylly** [comment]
Me too，and have u found a way to solve it？

**Comment by pupble** [comment]
have u found a way to solve it？

**Comment by mukulpatnaik** [comment]
Hi all @JiaLIU99 @zcylly @pupble sorry for the late response

I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
