### ISSUE TITLE
Save embeddings

### ISSUE THREAD

**Issue by pakaca** [mukulpatnaik/researchgpt#5]
Hello, thanks for this!

Should this also work well for longer texts like books? And if so, can it easily be made to cache the embeddings to disk? I'm assuming it's not that cheap nor fast to do that every time if it's a long thing, right?

**Comment by mukulpatnaik** [comment]
Hi @pakaca , I have added a way to store embeddings locally using redis. You can find that implementation [here](https://github.com/mukulpatnaik/researchgpt/blob/main/main-local-redis.py). You have to install redis and run `redis-serve` in a separate terminal for this to work
