### ISSUE TITLE
Error: Processing the pdf failed due to excess load. Please try again later. Check the URL if there is https:// at the beginning. If not, add it.

### ISSUE THREAD

**Issue by xiongzhenglong** [mukulpatnaik/researchgpt#50]
[量化.pdf](https://github.com/mukulpatnaik/researchgpt/files/11056490/default.pdf)

**Comment by keytuff** [comment]
I have the same question.

**Comment by keytuff** [comment]
console shows:No API key provided. 
I have set the OPENAI_API_KEY in the app.yaml file.
![image](https://user-images.githubusercontent.com/7944747/227422094-46846f58-bebd-4950-85d3-907ea15e19bb.png)

**Comment by fabianhug** [comment]
If this is still open: You need to add it to your machines environment variables if you're running it locally @keytuff

**Comment by mukulpatnaik** [comment]
Hi all @fabianhug @keytuff @xiongzhenglong @Ruairi-osul sorry for the late response.

I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!

Consider using www.dara.chat - it is a live version with some more optimizations and features that are not public yet. You can enter a link to a github repo too!
