### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by MrR0990** [mukulpatnaik/researchgpt#51]
from openai.embeddings_utils import get_embedding, cosine_similarity
File "/opt/homebrew/lib/python3.10/site-packages/openai/embeddings_utils.py", line 7, in <module>
from sklearn.decomposition import PCA
ModuleNotFoundError: No module named 'sklearn'

**Comment by mukulpatnaik** [comment]
Hi @MrR0990 you need to install sklearn. You can do this by running `pip3 install scikit-learn`.
