### ISSUE TITLE
How much money to parse a paper.

### ISSUE THREAD

**Issue by RizhaoCai** [mukulpatnaik/researchgpt#52]
The ChatGPT API is not free. 
According to the https://openai.com/pricing

![image](https://user-images.githubusercontent.com/37952703/227683102-5474994a-916a-4b8c-9995-18393e83ca2c.png)

Has anyone estimated how much money to analyze a paper?

**Comment by andupaz** [comment]
good question! would also be interested

**Comment by RizhaoCai** [comment]
> good question! would also be interested. I don't know if parsing works exactly like this, but here's my take on it.
> 
> Academic papers with the avg. length of 30 pages have around 7'500 words. If we pay 0.03 per 1k tokens, then at least $0.24 without the questions involved.
> 
> Does this make sense?

Yes. It may make sense. But it seems that the token number includes not only the uploaded part (paper text) but also the downloaded parts (output). The actual fee should be more than $0.24 and depends how many questions we ask for this paper.

I think $0.24 for a paper is expensive. What do you think, haha~. Have you used this researchgpt in your daily life?

**Comment by andupaz** [comment]
I have not used it, only saw the video. I would like to try it though. Let's say you get to extract everything you want from a paper for $1 - I don't think it's expensive, because you're saving on time that you would've used if you read it completely. In the end it's a matter of opportunity costs.

However, by not reading the paper and asking it questions, you're relying on the fact that it gives you a comprehensive answer, which you won't know for sure unless you've actually read the paper.

**Comment by RizhaoCai** [comment]
> I have not used it, only saw the video. I would like to try it though. Let's say you get to extract everything you want from a paper for $1 - I don't think it's expensive, because you're saving on time that you would've used if you read it completely. In the end it's a matter of opportunity costs.
> 
> However, by not reading the paper and asking it questions, you're relying on the fact that it gives you a comprehensive answer, which you won't know for sure unless you've actually read the paper. So I'm ambiguous towards it.

Yes.  Using the gpt tool may help when I struggle to understand a paper.  Unser such a case, the cost is definitely worthy  since it helps me learn the knowledge from the paper. If I use this gpt tool to do batch processing, there could be much unsless information, which could lead to a waste of money

**Comment by RizhaoCai** [comment]
> I have not used it, only saw the video. I would like to try it though. Let's say you get to extract everything you want from a paper for $1 - I don't think it's expensive, because you're saving on time that you would've used if you read it completely. In the end it's a matter of opportunity costs.
> 
> However, by not reading the paper and asking it questions, you're relying on the fact that it gives you a comprehensive answer, which you won't know for sure unless you've actually read the paper. So I'm ambiguous towards it.

Yes.  Using the gpt tool may help when I struggling understanding a paper. The cost is worthy if it helps me learn the knowledge from the paper. If I use this gpt tool to do batch processing, just for minor information, the cost is
