### ISSUE TITLE
I got this error during installation 

### ISSUE THREAD

**Issue by Jessy-Ding** [mukulpatnaik/researchgpt#53]
error: Command "/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_18025979-d416-4757-81ac-797dee762f1112z4f54t/croots/recipe/python-split_1654083066155/_build_env/bin/llvm-ar rcs build/temp.macosx-11.1-arm64-3.9/libnpymath.a build/temp.macosx-11.1-arm64-3.9/numpy/core/src/npymath/npy_math.o build/temp.macosx-11.1-arm64-3.9/build/src.macosx-11.1-arm64-3.9/numpy/core/src/npymath/ieee754.o build/temp.macosx-11.1-arm64-3.9/build/src.macosx-11.1-arm64-3.9/numpy/core/src/npymath/npy_math_complex.o build/temp.macosx-11.1-arm64-3.9/numpy/core/src/npymath/halffloat.o" failed with exit status 127
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mukulpatnaik** [comment]
Hi @Jessy-Ding sorry you're facing this issue. It seems to be an issue with your local python installation which unfortunately I cannot help with. Consider using the live version www.dara.chat - it is an updated version and has more features.

If you are interested in running it locally still, I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
