### ISSUE TITLE
what is best python3 version for this project?

### ISSUE THREAD

**Issue by shuod** [mukulpatnaik/researchgpt#56]
python3.10 or python 3.11 or ?
Thanks!

**Comment by mukulpatnaik** [comment]
Hi @shuod python3.10 should work best! 

P.S. I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. Thanks for trying it!
