### ISSUE TITLE
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by 826148133** [mukulpatnaik/researchgpt#59]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

anyone kind enough tell me what should i do

**Comment by margonguyen** [comment]
Hi, you need to install the right sckikit image. 
https://stackoverflow.com/questions/74356504/installation-error-of-scikit-image-in-python-3-11-0
This links might help

**Comment by mukulpatnaik** [comment]
Hi @826148133 sorry for the late response

I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. 

Also consider using the web app www.dara.chat, it has some features and optimizations that are not open source yet. Thanks for trying it!
