### ISSUE TITLE
Changing AI API

### ISSUE THREAD

**Issue by EverythingNeurodiversity** [mukulpatnaik/researchgpt#6]
Curious if you know how this can be modified to use hugging face all-minilm-l6-v2 for the embeddings and gpt-neo2.7b. Could be a similar way to do it for free (or low cost in production) I've been working on modifying it but haven't quite figured it out yet. keep running into one bug or another.

**Comment by EverythingNeurodiversity** [comment]
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2 and https://huggingface.co/EleutherAI/gpt-neo-2.7B

**Comment by mukulpatnaik** [comment]
Sounds really interesting! Have you made a fork where I can check out some of the modifications you're trying? I can think of a way for the embeddings but not sure about inference for gpt-neo

**Comment by EverythingNeurodiversity** [comment]
Not yet, having issues trying to get it working running locally on my machine. I think it this is sort of close to what is needed in the gpt function: 

` def gpt(self, prompt):
        print('Sending request to GPT-Neo')
        r = response = requests.post(HF_API_URL, headers=HF_headers, json=prompt)
        answer = r.choices[0]['text']
        print('Done sending request to GPT-3')
        response = {'answer': answer, 'sources': sources}
        return response
`

where HF_API_URL = API_URL = "https://api-inference.huggingface.co/models/EleutherAI/gpt-neo-2.7B"
and headers = {"Authorization": "Bearer Hugging face API key"}

Was trying to test it with some dummy data on the HF playground but haven't figured it out yet. Will upload a fork if I get something going.

**Comment by mukulpatnaik** [comment]
@EverythingNeurodiversity Sounds great, looking forward to it!
