### ISSUE TITLE
error:program get stopped when typing "python main-local.py"

### ISSUE THREAD

**Issue by fengan078525** [mukulpatnaik/researchgpt#61]
it stops when typing "python main-local.py",can some one comment and help me?
when it comes to this stage:
![无标题](https://user-images.githubusercontent.com/131636258/233993311-f433d675-200f-4bff-9705-306635e450eb.png)
it stopped, can some one help me?

**Comment by mukulpatnaik** [comment]
Hi @fengan078525 sorry for the late response, I have made a major refactor of the code, fixing many issues and moving from flask to fastapi, if you are still interested please consider running git fetch to update your code to the latest version and try following the steps in the README to run the app. If git fetch does not work, consider cloning the repo again. Thanks for trying it!
