### ISSUE TITLE
Stuck in "Calculating embeddings"

### ISSUE THREAD

**Issue by xuyangm** [mukulpatnaik/researchgpt#62]
Hi, I run the app successfully. But it is stuck in "Calculating embeddings" state. I can type messages but get no reply.
![pic1](https://user-images.githubusercontent.com/16891612/234296234-460ed158-ba6d-4069-9662-435395442209.jpg)
![pic2](https://user-images.githubusercontent.com/16891612/234296268-3c569004-34c3-4f52-825a-743018a689a8.jpg)

**Comment by mukulpatnaik** [comment]
Hi @xuyangm sorry for the late response. I recently pushed a major refactor to the code. Please run `git fetch` to get the latest changes and try again. Let me know if you have any questions!
