### ISSUE TITLE
how it works!?

### ISSUE THREAD

**Issue by JorgePerezRey** [mukulpatnaik/researchgpt#63]
Hi there

ok, my undertanding on computers is not advanced and what i want is to chat with a pdf. I followed all the instructions, installing ubuntu, github desktop, redis... etc... To be honest i don´t know what I even did... 
The thing is that i dont know what do I have to do to run researchgpt to chat with the pdf´s.
thanks in advance ;)

**Comment by mukulpatnaik** [comment]
Hi @JorgePerezRey, thanks for trying it out! (You did not need to install Ubuntu btw, hope you didn't install a whole new OS just to try this). In order to run the webapp, you want to, on your terminal, navigate to the folder where you have cloned this repo. On most systems you can do this my running `cd` followed by the path where the `researchgpt` folder is. Once you're in there you can paste in this command `uvicorn main:app --reload` and you should be good to go! You can also try out the online demo at www.dara.chat

Feel free to follow up with any more questions if you're having issues!

**Comment by JorgePerezRey** [comment]
thanks @mukulpatnaik for your answer. yes, installed ubuntu, but that is not an important issue, the thing is that I dont know how to run reseachgpt, 
I attach you a screen shot, and then what??
Thanks so much
![Sin título](https://github.com/mukulpatnaik/researchgpt/assets/135229023/7b3a8fda-e4ca-4740-80de-8c9474913a50)

**Comment by mukulpatnaik** [comment]
Hi @JorgePerezRey the error suggests that you don't have redis installed. First exit out of the application by hitting `ctrl+C`. Please install redis by typing `pip install redis` (My apologies, I should have put it in the `requirements.txt`). I have also just pushed an update, so please also run `git fetch`.

In summary here are the commands you want to run in your terminal in order:

`ctrl+C`
`git fetch`
`pip install redis`

After this, run `uvicorn main:app --reload` and it should work. Consider using the webapp www.dara.chat as it has many optimizations that I have not made public yet. Let me know if you have anymore questions!

**Comment by JorgePerezRey** [comment]
Hi @mukulpatnaik thanks for your hard work trying to explain me how to do it. I´m struggling to make it work and that is because my ignorance on computers.  so, the intructions you gave me are to use research gpt locally in my pc?? and then dara.chat is another way to use it? I tried but it is always "...loading", and finally the chrome extensión.
I understand if you dont want to spend your time on this, but I´m still grateful for the time you already spend on it.
Thanks so much
![Sin título](https://github.com/mukulpatnaik/researchgpt/assets/135229023/fbb7d2dc-bb88-4c4b-b766-fe0fafcbea09)
![Sin título](https://github.com/mukulpatnaik/researchgpt/assets/135229023/a1d1b9fa-fcd4-4580-8572-f74b4402afd2)
![Sin título](https://github.com/mukulpatnaik/researchgpt/assets/135229023/349c8ed5-8474-4fe9-b006-5f588301bfe7)

**Comment by mukulpatnaik** [comment]
Hi @JorgePerezRey no worries, you're doing great! These are actually mistakes on my part. I'm happy to help. The error indicates jinja2 is missing. Again, my fault- I thought it would be a part of fastapi. I have now included it in the requirements.txt. You can install it using `pip install jinja2`, and hopefully it should work!

Regarding the web app at https://dara.chat, it seems to work fine for me. Please make sure you have entered your OpenAI key correctly. You can re-enter it in the sidebar.
<img width="1512" alt="Screenshot 2023-06-04 at 12 28 54 PM" src="https://github.com/mukulpatnaik/researchgpt/assets/36257370/70c3138e-d0ad-4c5a-a7f9-23248fbcfc77">

Regarding the chrome extension, it can only be used on websites currently. For pdfs and docx, please use the web app. Again, please make sure your OpenAI key is entered correctly and has enough credits to work. Thanks! Let me know if there are any more problems

**Comment by JorgePerezRey** [comment]
Working!!! thanks so much for your help and your work! Very useful tool!
