### ISSUE TITLE
No app started when it says "Application startup complete"

### ISSUE THREAD

**Issue by BrianZ96** [mukulpatnaik/researchgpt#67]
Hi mukulpatnaik, 

I have followed the instruction and installed a Ubuntu on my Windows, then I have cloned and installed all the required resources in the Linux system, also added my API key. But when I use the uvicorn command, it shows something like this:
<img width="712" alt="image" src="https://github.com/mukulpatnaik/researchgpt/assets/38589072/b3456d3a-87e1-4d94-a481-791063fab301">
then nothing happens more, I don't see the interface of the application. What should I do next?

**Comment by Lily-Le** [comment]
You can enter the url http://127.0.0.1:8000 in your browser. :D
