### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by fernandosn1977** [mukulpatnaik/researchgpt#9]
I couldn't install it after two attempts.

![20-02--2023_19-23-35](https://user-images.githubusercontent.com/105297993/220207225-eb94f7a9-644b-4760-88a8-c04baf80ff93.jpg)

**Comment by mukulpatnaik** [comment]
Hi @fernandosn1977  sorry to hear you're having installation issues. Please try removing the version constraints in `requirements.tx` You could also try installing the packages listed in requirements.txt one by one manually. Let me know if that helps.
